### ISSUE TITLE
Couchpotato won't update in-app

### ISSUE THREAD

**Issue by ausey00** [Influencer/UNplugged#24]
Here's the log

05-29 21:38:14 ERROR [hpotato.core.plugins.base] Failed opening url in FileManager: https://github.com/RuudBurger/CouchPotatoServer/tarball/master Traceback (most recent call last):
  File "/usr/local/couchpotato_v2/couchpotato/core/plugins/base.py", line 148, in urlopen
    response = urllib2.urlopen(request, timeout = timeout)

HTTPError: HTTP Error 404: Not Found
05-29 21:38:14 ERROR [hpotato.core.plugins.file] Failed downloading file https://github.com/RuudBurger/CouchPotatoServer/tarball/master: Traceback (most recent call last):
  File "/usr/local/couchpotato_v2/couchpotato/core/plugins/file/main.py", line 103, in download
    filedata = self.urlopen(url, *_urlopen_kwargs)
  File "/usr/local/couchpotato_v2/couchpotato/core/plugins/base.py", line 148, in urlopen
    response = urllib2.urlopen(request, timeout = timeout)
  File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 429, in error
    result = self._call_chain(_args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.6/urllib2.py", line 605, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 429, in error
    result = self._call_chain(_args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.6/urllib2.py", line 605, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 435, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

05-29 21:38:14 ERROR [potato.core._base.updater] Failed updating: Traceback (most recent call last):
  File "/usr/local/couchpotato_v2/couchpotato/core/_base/updater/main.py", line 278, in doUpdate
    tar = tarfile.open(destination)
  File "/usr/lib/python2.6/tarfile.py", line 1644, in open
    raise ValueError("nothing to open")
ValueError: nothing to open

**Comment by Influencer** [comment]
Its working fine on my end, on the thread in the forum look a few pages back, there was a similar issue that caused it to fail then, might work for you. Since its a 404 error there is sadly nothing I can do to fix it, it is an issue with either couchpotato or github.
